// angular-compare/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.sass']
})
export class HeaderComponent implements OnInit {

  toggleNav = false;
  constructor() { }

  ngOnInit(): void {
  }

}


<div class="nav has-shadow">
  <div class="container">
    <div class="nav-left">
      <a routerLink="/" class="nav-item">Compare Company</a>
    </div>

    <div class="nav-toggle" (click)="toggleNav = !toggleNav;" [ngClass]="{'is-active': toggleNav}">
      <span></span>
      <span></span>
      <span></span>
    </div>

    <div class="nav-right nav-menu" [ngClass]="{'is-active': toggleNav}">

      <a routerLink="/" class="nav-item r-item">Home</a>
      <a class="nav-item r-item">Features</a>
      <a class="nav-item r-item">About</a>
      <a routerLink="/faq" class="nav-item r-item">FAQ</a>

      <div class="nav-item">
        <p class="control">
          <a class="button is-primary is-outlined">
            <span class="icon">
              <i class="fa fa-download"></i>
            </span>
            <span>Join Now</span>
          </a>
        </p>
      </div>

    </div>
  </div>
</div>

// react-compare/src/components/Header/Header.js
import React, { Component } from 'react';
import './Header.css';
import { Link } from 'react-router-dom';

class Header extends Component {

  constructor(props) {
      super(props);
      this.state = {isToggleOn: false};

      this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
      this.setState(prevState => ({
          isToggleOn: !prevState.isToggleOn
      }));
  }

  render() {

    let menuActive = this.state.isToggleOn ? 'is-active' : '';
    
    return (
          <div className="nav has-shadow">
      <div className="container">
        <div className="nav-left">
          <a className="nav-item">Compare Company</a>
        </div>

        <span className={'nav-toggle '+menuActive} onClick={this.handleClick}>
          <span></span>
          <span></span>
          <span></span>
        </span>

        <div className={'nav-right nav-menu '+menuActive}>

          <Link to="/" className="nav-item r-item">Home</Link>
          <Link to="/faq" className="nav-item r-item">Features</Link>
          <Link to="/faq" className="nav-item r-item">About</Link>
          <Link to="/faq" className="nav-item r-item">FAQ</Link>

          <div className="nav-item">
            <p className="control">
              <a className="button is-primary is-outlined">
                <span className="icon">
                  <i className="fa fa-download"></i>
                </span>
                <span>Join Now</span>
              </a>
            </p>
          </div>

        </div>
      </div>
    </div>
    );
  }
}

export default Header;
